YateMate/Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('login/', views.login_view, name='login'),
    path('login/logout/', views.logout_view, name='logout'),
    path('register/',views.register,name='register'),
    path('enable_accounts/',views.usuarios_inhabilitados,name='enable_accounts'),
    path('habilitar-usuario/<int:usuario_id>/', views.habilitar_usuario, name='habilitar_usuario'),
    path('listado_clientes/',views.listado_clientes, name='listado_clientes'),
    path('moroso_clientes/<int:cliente_id>/',views.moroso_clientes, name='moroso_clientes'),
    path('cancelar_deuda/<int:cliente_id>/',views.cancelar_deuda, name='cancelar_deuda'),
    path('eliminar_usuario/<int:cliente_id>/', views.eliminar_cuenta , name='eliminar_usuario'),
    path('mi_perfil/<int:cliente_id>/',views.mi_perfil, name="perfil"),
    path('eliminar_cuenta/<int:cliente_id>/',views.eliminar_micuenta, name="eliminar_micuenta"),
    path('eliminar-mensaje/', views.eliminar_mensaje, name='eliminar_mensaje'),
]

YateMate/Trueque/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("list/", views.list, name="list"),
    path("list_publication/", views.list_publication, name="list_publication"),
    path("list_publication_boat/", views.list_publication_boat, name="list_publication_boat"),
    path("mis_publicaciones/", views.mis_publicaciones, name="ver_mis_publicaciones"),
    path("solicitudes_trueque_objeto/<int:publicacion_id>/", views.solicitudes_trueque_objeto, name="solicitudes_trueque_objeto"),
    path("solicitudes_trueque_embarcacion/<int:publicacion_id>/", views.solicitudes_trueque_embarcacion, name="solicitudes_trueque_embarcacion"),
    path('saber_mas/<int:id>/<str:tipo_objetos>/', views.saber_mas, name='saber_mas'),
    path("eliminarObjeto/<int:id>/", views.eliminarObjeto, name='eliminar_objeto'),
    path("eliminarEmbarcacion/<int:id>/", views.eliminarEmbarcacion, name='eliminar_embarcacion'),
    path("solisitar_trueque/<int:publicacion_id>/<str:tipo>/",views.solisitar_trueque, name="solisitar_trueque"),
    path("darDeBajaEmbarcacion/<int:publicacion_id>/",views.darDeBajaEmbarcacion, name="eliminarPublicacionEmbarcacion"),
    path("darDeBajaObjeto/<int:publicacion_id>/",views.darDeBajaObjeto, name="eliminarPublicacionObjeto"),
    path("solicitud_embarcacion/<int:publicacion_id>/",views.solicitud_embarcacion, name="solicitud_embarcacion"),
    path("solicitud_objeto_valioso/<int:publicacion_id>/", views.solicitud_objeto_valioso, name="solicitud_objeto_valioso"),
    path("rechazar_trueque/<int:solicitud_id>/<str:tipo>/", views.rechazar_trueque, name="rechazar_trueque"),
    path("iniciarSolicitudTrueque/<int:solicitudID>/<int:publicacionID>/<str:tipo_objetos>/", views.iniciar_solicitud_de_trueque, name="iniciarSolicitudDeTrueque"),
    path('enviar_mensaje/', views.enviar_mensaje, name='enviar_mensaje'),
    path('registrar_Objeto_Valioso/', views.registrar_Objeto_Valioso, name='registrar_Objeto_Valioso'),
    path('registrar_publicacion_boat/', views.registrar_Embarcacion, name='registrar_publicacion_boat'),
    path('finalizar_trueque/<int:publicacion_id>/<str:tipo_obj>/', views.finalizar_trueque, name='finalizar_trueque'),
    path('eliminar_mensaje/<int:mensaje_id>/', views.eliminar_mensaje, name='eliminar_mensaje'),
    path('denunciar/<int:sender_id>/<str:msj>/<int:mensaje_id>/', views.denunciar_usuario, name='denunciar_usuario'),
    path('ver_mensajes_emb/<int:objeto_id>/', views.ver_mensajes_emb, name='ver_mensajes_emb'),
    path('ver_mensajes_obj/<int:objeto_id>/', views.ver_mensajes_obj, name='ver_mensajes_obj'),
    path('ver_informacion_adm/<int:publi_id>/<str:tipo_objeto>/', views.ver_informacion_adm, name='ver_informacion_adm'),
    path('mensajes_denunciados/', views.mensajes_denunciados, name='mensajes_denunciados'),
    path('descartar_denuncia/<int:denuncia_id>/', views.descartar_denuncia, name='descartar_denuncia'),
    path('censurar_mensaje/<int:denuncia_id>/', views.censurar_mensaje, name='censurar_mensaje'),
]

YateMate/YateMate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Valoracion.urls")),
    path("", include("Home.urls")),
    path("", include("Trueque.urls")),
    path("", include("Register.urls")),
    path("", include("Amarra.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

YateMate/Trueque/models.py
from django.db import models
from Register.models import Embarcacion, User

#ObjetoValioso
class Publicacion_ObjetoValioso(models.Model):
    ESTADO_CHOICES = (
        ('Vigente', 'Vigente'),
        ('Proceso', 'Proceso'),
        ('Finalizado', 'Finalizado'),
    )

    tipo = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    descripcion = models.TextField()
    estado = models.CharField(max_length=50)
    matricula = models.CharField(max_length=50)  # Agregado el campo matricula
    dueño = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    foto = models.ImageField(upload_to='static/img_o/')

    def __str__(self):
        return f"{self.tipo} - {self.marca}"
       
#Embarcaciones
class Publicacion_Embarcacion(models.Model):
    ESTADO_CHOICES = (
        ('Vigente', 'Vigente'),
        ('Proceso', 'Proceso'),
        ('Finalizado', 'Finalizado'),
    )
    embarcacion = models.ForeignKey(Embarcacion, on_delete=models.CASCADE)
    descripcion = models.TextField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_fantasia

class Solicitud_Embarcaciones(models.Model):
    publicacion = models.ForeignKey(Publicacion_Embarcacion, on_delete=models.CASCADE)
    usuario_interesado = models.ForeignKey(User, on_delete=models.CASCADE, related_name='solicitudes_embarcaciones')
    iniciado = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Solicitud de {self.usuario_interesado} para {self.publicacion}'

class Solicitud_ObjetosValiosos(models.Model):
    publicacion = models.ForeignKey(Publicacion_ObjetoValioso, on_delete=models.CASCADE)
    usuario_interesado = models.ForeignKey(User, on_delete=models.CASCADE, related_name='solicitudes_objetos_valiosos')
    iniciado = models.BooleanField(default=False)

    def __str__(self):
        return f'Solicitud de {self.usuario_interesado} para {self.publicacion}'
    
class MensajeSolicitudObjetosValiosos(models.Model):
    mensaje = models.TextField()
    solicitud_objeto_valioso = models.ForeignKey('Solicitud_ObjetosValiosos', on_delete=models.CASCADE)

class MensajeSolicitudEmbarcaciones(models.Model):
    mensaje = models.TextField()
    solicitud_embarcacion = models.ForeignKey('Solicitud_Embarcaciones', on_delete=models.CASCADE)

class Conversacion(models.Model):
    dueño_publicacion = models.ForeignKey(User, related_name='conversations_initiated', on_delete=models.CASCADE)
    solicitante = models.ForeignKey(User, related_name='conversations_received', on_delete=models.CASCADE)
    creado = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('dueño_publicacion', 'solicitante')

    def get_mensajes(self):
        return Mensajes_chat.objects.filter(conversacion=self).order_by('enviado_a')

    def get_participantes(self):
        return [self.dueño_publicacion, self.solicitante]

    def __str__(self):
        return f'Conversación entre {self.dueño_publicacion.nombre} y {self.solicitante.nombre}'


class Mensajes_chat(models.Model):
    conversacion = models.ForeignKey(Conversacion, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, to_field='id')
    mensaje_texto = models.TextField()
    enviado_a = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.sender.nombre}: {self.mensaje_texto[:30]}... ({self.enviado_a.strftime("%Y-%m-%d %H:%M:%S")})'

    @classmethod
    def get_ordered_messages(cls, conversation_id):
        return cls.objects.filter(conversacion_id=conversation_id).order_by('enviado_a')


class Denuncia(models.Model):
    denunciado = models.ForeignKey(User, related_name='denuncias_recibidas', on_delete=models.CASCADE)
    denunciante = models.ForeignKey(User, related_name='denuncias_realizadas', on_delete=models.CASCADE)
    mensaje_texto = models.TextField()
    mensaje = models.ForeignKey(Mensajes_chat, related_name='mensaje', on_delete=models.CASCADE, default=1)

    class Meta:
        unique_together = ('denunciado', 'denunciante', 'mensaje_texto')  # Asegura que no se pueda duplicar la misma denuncia

    def __str__(self):
        return f'Denuncia de {self.denunciante.username} contra {self.denunciado.username}'

YateMate/Trueque/templates/list.html
{% extends "base.html" %}

{% block title %}
Mi Página de Inicio
{% endblock %}

{% block content %}
<style>
    /* Estilo para cada tarjeta */
    .card {
        background-color: #f8f9fa;
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
    }

    /* Estilo para el título de la tarjeta */
    .card-title {
        color: #007bff;
        font-size: 1.5rem;
        margin-bottom: 10px;
    }

    /* Estilo para el botón de la tarjeta */
    .btn-card {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
        margin-bottom: 10px;
    }

    /* Estilo para el formulario de filtro */
    .filter-form {
        margin-bottom: 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .filter-form label {
        margin-right: 10px;
        font-weight: bold;
    }

    .filter-form select {
        padding: 5px;
        border-radius: 3px;
        border: 1px solid #ced4da;
    }

    .filter-form button {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .error-message {
        background-color: #ffdddd;
        color: #d8000c;
        padding: 10px;
        border-radius: 5px;
        margin-top: 10px;
    }
</style>

<!-- Formulario de filtro por estado y tipo de publicación -->
<form class="filter-form" method="GET" action="">
    <div style="display: flex; align-items: center;">
        <div style="margin-right: 10px;">
            <label for="estado">Filtrar por Estado:</label>
            <select name="estado" id="estado">
                <option value="Vigente"{% if request.GET.estado == 'Vigente' %} selected{% endif %}>Vigente</option>
                <option value="Proceso"{% if request.GET.estado == 'Proceso' %} selected{% endif %}>Proceso</option>
                <option value="Finalizado"{% if request.GET.estado == 'Finalizado' %} selected{% endif %}>Finalizado</option>
            </select>
        </div>
        <div>
            <label for="tipo">Filtrar por Tipo de Publicación:</label>
            <select name="tipo" id="tipo">
                <option value="objetos valiosos"{% if request.GET.tipo == 'objetos valiosos' %} selected{% endif %}>Objetos Valiosos</option>
                <option value="embarcaciones"{% if request.GET.tipo == 'embarcaciones' %} selected{% endif %}>Embarcaciones</option>
            </select>
        </div>
        <button type="submit" style="margin-left: 10px;">Filtrar</button>
    </div>
</form>

{% if objetos %}
    <h2>Publicaciones</h2>
    {% for objeto in objetos %}
        <div class="card">
            <h3 class="card-title">
                {% if objeto.embarcacion.nombre_fantasia %}
                    {{ objeto.embarcacion.nombre_fantasia }}
                {% else %}
                    {{ objeto.marca }}
                {% endif %}
                {% if objeto.embarcacion.tipo %}
                    - {{ objeto.embarcacion.tipo }}
                {% else %}
                    - {{ objeto.tipo }}
                {% endif %}
            </h3>
            <p>{{ objeto.descripcion|truncatechars:70 }}</p>
            <a href="{% url 'saber_mas' id=objeto.id tipo_objetos=tipo_objetos %}" class="btn btn-card">Saber más</a>

            {% if request.GET.estado == 'Proceso'%}
                 <a href="{% url 'finalizar_trueque' publicacion_id=objeto.id tipo_obj=tipo_objetos %}" class="btn btn-card finalizar-trueque" data-url="{% url 'finalizar_trueque' publicacion_id=objeto.id tipo_obj=tipo_objetos %}">Finalizar Trueque</a>
                <div class="messages" style="display: none;"></div> <!-- Div para mostrar el mensaje -->
            {% endif %}

            {% if request.GET.estado == 'Proceso' or request.GET.estado == 'Finalizado' %}
                {% if objeto.embarcacion.nombre_fantasia %}
                    <a href="{% url 'ver_mensajes_emb' objeto.id %}" class="btn btn-card">Ver mensajes</a>
                {% else %}
                    <a href="{% url 'ver_mensajes_obj' objeto.id %}" class="btn btn-card">Ver mensajes</a>
                {% endif %}
            {% endif %}
            {% if request.GET.estado == 'Finalizado' and objeto.embarcacion%}
                <a href="{% url 'ver_informacion_adm' objeto.id tipo_objetos %}" class="btn btn-card">Ver información</a>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    <p>No se cuenta con Publicaciones.</p>
{% endif %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.finalizar-trueque').forEach(function(button) {
            button.addEventListener('click', function(event) {
                event.preventDefault();
                const url = button.getAttribute('data-url');
                fetch(url, {
                    method: 'GET',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.moroso) {
                        // Mostrar alerta si el usuario es moroso
                        window.alert('La operación no se puede realizar hasta que el usuario regularice sus deudas');
                    } else {
                        window.location.reload(); // Recargar la página si no hay problema
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    });
</script>

{% endblock %}

YateMate/Trueque/templates/list_publication.html
{% extends "base.html" %}

{% block title %}
Lista publicaciones
{% endblock %}

{% block content %}
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
<style>
    /* Estilo para cada tarjeta */
    .card {
        background-color: #f8f9fa;
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
    }

    /* Estilo para el título de la tarjeta */
    .card-title {
        color: #007bff;
        font-size: 1.5rem;
        margin-bottom: 10px;
    }

    /* Estilo para el botón de la tarjeta */
    .btn-card {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
    }
    /* Estilo para el formulario de filtro */
    .filter-form {
        margin-bottom: 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .filter-form label {
        margin-right: 10px;
        font-weight: bold;
    }

    .filter-form select {
        padding: 5px;
        border-radius: 3px;
        border: 1px solid #ced4da;
    }

    .filter-form button {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }
    .publicaciones-container {
        padding-bottom: 100px; /* Espacio inferior para evitar que quede oculto por el footer */
    }
</style>
<form class="filter-form" method="GET" action="">
    <div style="display: flex; align-items: center;"> <!-- Contenedor de elementos flexibles -->
        <div style="margin-right: 10px;"> <!-- Divisor para el menú desplegable -->
            <label for="tipo">Filtrar por Tipo de Publicación:</label>
            <select name="tipo" id="tipo">
                <option value="objetos valiosos" {% if request.GET.tipo == 'objetos valiosos' %}selected{% endif %}>Objetos Valiosos</option>
                <option value="embarcaciones" {% if request.GET.tipo == 'embarcaciones' %}selected{% endif %}>Embarcaciones</option>
            </select>
        </div>
        <button type="submit">Filtrar</button>
    </div>
</form>
<div class="publicaciones-container">
{% if objetos %}
    <h2>Publicaciones</h2>
    {% for objeto in objetos %}
        <div class="card">
            <h3 class="card-title">
                {% if objeto.embarcacion.nombre_fantasia %}
                    {{ objeto.embarcacion.nombre_fantasia }}
                {% else %}
                    {{ objeto.marca }}
                {% endif %}
                {% if objeto.embarcacion.tipo%}
                    - {{ objeto.embarcacion.tipo }}
                {% else %}
                    - {{ objeto.tipo }}
                {% endif %}
            </h3>
            <p>{{ objeto.descripcion|truncatechars:70 }}</p>
            <a href="{% url 'saber_mas' id=objeto.id tipo_objetos=tipo_objetos %}" class="btn btn-card">Saber más</a>
        </div>
    {% endfor %}
</div>
{% else %}
    <p>No se cuenta con Publicaciones.</p>
{% endif %}

{% endblock %}

YateMate/Trueque/templates/list_publication_boat.html
{% extends "base.html" %}

{% block title %}
Mi Página de Inicio
{% endblock %}

{% block content %}
<style>
    /* Estilo para cada tarjeta */
    .card {
        background-color: #f8f9fa;
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
    }

    /* Estilo para el título de la tarjeta */
    .card-title {
        color: #007bff;
        font-size: 1.5rem;
        margin-bottom: 10px;
    }

    /* Estilo para el botón de la tarjeta */
    .btn-card {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
    }
</style>

{% if embarcaciones_vigentes %}
    <h2>Publicaciones</h2>
    {% for embarcacion in  embarcaciones_vigentes %}
        <div class="card">
            <h3 class="card-title">{{ embarcacion.embarcacion.tipo }} - {{ embarcacion.embarcacion.nombre_fantasia }}</h3>
            <p>{{ embarcacion.descripcion|truncatechars:70 }}</p>
            <a href="{% url 'saber_mas' id=embarcacion.id tipo_objetos=tipo_objetos %}" class="btn btn-card">Saber más</a>
        </div>
    {% endfor %}
{% else %}
    <p>No se cuenta con Publicaciones.</p>
{% endif %}
{% endblock %}

YateMate/Trueque/templates/mensajes_denunciados.html
{% extends "base.html" %}

{% block title %}
Mi Página de Inicio
{% endblock %}

{% block content %}
<style>
        .message-body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f0f0f0;
            padding: 20px;
            margin-bottom: 60px;
        }
        .message-container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .message-container h1 {
            text-align: center;
            color: #333;
        }
        .message-container ul {
            list-style-type: none;
            padding: 0;
        }
        .message-container li {
            background-color: #f9f9f9;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
            border-left: 3px solid #3498db;
        }
        .message-info {
            display: flex;
            justify-content: space-evenly;
            align-items: center;
            margin-bottom: 5px;
        }
        .message-sender {
            font-weight: bold;
        }
        .message-date {
            color: #888;
        }
        .message-text {
            margin-left: 20px;
        }
        .btn-container {
            text-align: center; /* Centra horizontalmente los elementos inline */
        }

        .btn-card {
            background-color: #007bff;
            color: #fff;
            padding: 5px 10px;
            text-decoration: none;
            border-radius: 3px;
            display: inline-block;
        }
</style>

    <div class="message-body">
        <div class="message-container">
            <h1>Mensajes denunciados</h1>
            <ul>
                {% for mensaje in mensajes %}
                <li>
                    <div class="message-info">
                        <span class="message-sender">{{ mensaje.denunciado.nombre }}</span>
                        <span class="message-sender">{{ mensaje.denunciado.apellido }}</span>
                        <span class="message-sender">{{ mensaje.denunciado.mail }}</span>
                        <span class="message-sender">{{ mensaje.denunciado.dni }}</span>
                    </div>
                    <div class="message-text">
                        {{ mensaje.mensaje_texto }}
                    </div>
                    <div class="btn-container">
                        <a href="{% url 'censurar_mensaje' mensaje.id %}" class="btn btn-card" onclick="return confirm('¿Estás seguro que quiere censurar el mensaje?')">Censurar</a>
                        <a href="{% url 'descartar_denuncia' mensaje.id %}" class="btn btn-card" onclick="return confirm('¿Estás seguro de descartar la denuncia?')">Descartar denuncia</a>
                    </div>
                </li>
                {% empty %}
                <li>No hay mensajes para mostrar.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

YateMate/Trueque/templates/registrar_publicacion_boat.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Registrar Publicación de Objeto Valioso
{% endblock %}

{% block content %}
<style>
       .btn-card {
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
        margin-bottom: 20px; /* Añade espacio inferior */
    }

    .container-r {
        display: flex;
        width: 50%;
        margin: auto; /* Centra horizontalmente el contenedor */
        margin-top: 10px;
        align-items: center;
    }

    /* Estilos para el recuadro del formulario */
    .recuadroLogin-r {
        background-color: #b8dee0;
        height: 100%;
        width: 100%;
        border-radius: 20px;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);
        -webkit-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);
        -moz-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);
        border-left: 3px solid #3c667d;
    }

    /* Estilos para el contenedor del formulario */
    .form-container {
        display: flex;
        justify-content: center; /* Centrar horizontalmente */
        align-items: center; /* Centrar verticalmente */
        min-height: 70vh; /* Altura mínima para centrar verticalmente */
        background-color: #b8dee0; /* Fondo para mejor visualización */
        padding: 20px; /* Espaciado interno */
    }

    /* Estilos para el formulario */
    .form-wrapper {
        background-color: #b8dee0;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        max-width: 500px; /* Ancho máximo del formulario */
        width: 100%; /* Ancho completo dentro del contenedor */
    }
    h1 {
        white-space: nowrap; /* Evita que el texto se divida en varias líneas */
        text-align: center; /* Centrar el texto */
    }
    textarea {
        width: 100%; /* Ancho completo dentro del contenedor */
        min-height: 50px; /* Altura mínima del textarea */
        resize: vertical; /* Permite cambiar el tamaño verticalmente */
    }
</style>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<body>
    <div class="container-r">
        <div class="recuadroLogin-r">
            <div class="form-container">
                <div class="form-wrapper">
                    <button type="button" id="publicar-embarcacion" class="">Publicar Objeto Valioso</button>
                    <h1>Registrar Publicación de Embarcacion</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn-card">Crear Publicación</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const publicarBtn = document.getElementById('publicar-embarcacion');
        if (publicarBtn) {
            publicarBtn.addEventListener('click', () => {
                window.location.href = "http://127.0.0.1:8000/registrar_Objeto_Valioso/"; // Reemplaza 'ruta_de_redireccion' con la URL a la que deseas redirigir
            });
        }
    });
</script>
{% endblock %}

YateMate/Trueque/templates/solisitar_trueque.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Solicitar Trueque
{% endblock %}

{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div>
    <p>En el cuerpo del mensaje indique por qué objeto valioso quiere hacer el trueque.</p>
    <label for="id_mensaje">Mensaje:</label>
    <textarea id="id_mensaje" name="mensaje" rows="4" cols="50"></textarea>
  </div>
  <input type="hidden" id="tipo_objeto" name="tipo_objeto" value="{{ tipo_objetos }}">
  <input type="hidden" id="publicacion_id" name="publicacion_id" value="{{ objeto.id }}">
  <button type="button" class="btn btn-primary mt-3" onclick="enviarSolicitud()">Solicitar</button>
</form>

<script>
  function enviarSolicitud() {
    var tipo = document.getElementById("tipo_objeto").value;
    var publicacionId = document.getElementById("publicacion_id").value;
    var mensaje = document.getElementById("id_mensaje").value; // Obtener el mensaje
    
    if (tipo === "Embarcaciones") {
      window.location.href = `/solicitud_embarcacion/${publicacionId}/?mensaje_solicitud=${mensaje}`; // Enviar el mensaje como parámetro en la URL
    } else if (tipo === "Objetos Valiosos") {
      window.location.href = `/solicitud_objeto_valioso/${publicacionId}/?mensaje_solicitud=${mensaje}`; // Enviar el mensaje como parámetro en la URL
    } else {
      alert("Tipo de objeto no válido.");
    }
  }
</script>
{% endblock %}